FROM java:8-jre
COPY ./target/foodrecommendation-0.0.1-SNAPSHOT.jar /usr/src/./target/foodrecommendation-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src
CMD ["java","-jar","foodrecommendation-0.0.1-SNAPSHOT.jar"]